import { useTranslation } from 'react-i18next';

export function useContent() {
  const { t } = useTranslation();

  return {
    brand: t('brand'),
    nav: {
      home: t('nav.home'),
      trade: t('nav.trade'),
      quote: t('nav.quote'),
      about: t('nav.about'),
      start: t('nav.start'),
      login: t('nav.login'),
    },
    hero: {
      title: t('hero.title'),
      subtitle: t('hero.subtitle'),
    },
    liveTicker: {
      pair: t('liveTicker.pair'),
      status: t('liveTicker.status'),
      bullet: t('liveTicker.bullet'),
    },
    trading: {
      title: t('trading.title'),
      description: t('trading.description'),
      ctaTitle: t('trading.ctaTitle'),
      ctaDescription: t('trading.ctaDescription'),
      ctaButton: t('trading.ctaButton'),
      features: [
        {
          title: t('trading.features.0.title'),
          description: t('trading.features.0.description'),
        },
        {
          title: t('trading.features.1.title'),
          description: t('trading.features.1.description'),
        },
        {
          title: t('trading.features.2.title'),
          description: t('trading.features.2.description'),
        },
        {
          title: t('trading.features.3.title'),
          description: t('trading.features.3.description'),
        },
      ],
    },
    about: {
      title: t('about.title'),
      quote: t('about.quote'),
      text: t('about.text'),
      highlight: t('about.highlight'),
      mission: {
        title: t('about.mission.title'),
        description: t('about.mission.description'),
      },
      vision: {
        title: t('about.vision.title'),
        description: t('about.vision.description'),
      },
      values: {
        title: t('about.values.title'),
        list: [
          t('about.values.list.0'),
          t('about.values.list.1'),
          t('about.values.list.2'),
          t('about.values.list.3'),
          t('about.values.list.4'),
          t('about.values.list.5'),
        ],
      },
      history: {
        title: t('about.history.title'),
        text: t('about.history.text'),
        quote: t('about.history.quote'),
      },
      whatWeDo: {
        title: t('about.whatWeDo.title'),
        quote: t('about.whatWeDo.quote'),
        pfTitle: t('about.whatWeDo.pfTitle'),
        pfList: [
          t('about.whatWeDo.pfList.0'),
          t('about.whatWeDo.pfList.1'),
          t('about.whatWeDo.pfList.2'),
          t('about.whatWeDo.pfList.3'),
          t('about.whatWeDo.pfList.4'),
        ],
        pjTitle: t('about.whatWeDo.pjTitle'),
        pjList: [
          t('about.whatWeDo.pjList.0'),
          t('about.whatWeDo.pjList.1'),
          t('about.whatWeDo.pjList.2'),
          t('about.whatWeDo.pjList.3'),
          t('about.whatWeDo.pjList.4'),
        ],
      },
      ecosystem: {
        title: t('about.ecosystem.title'),
        quote: t('about.ecosystem.quote'),
        text: t('about.ecosystem.text'),
        items: [
          {
            title: t('about.ecosystem.items.0.title'),
            description: t('about.ecosystem.items.0.description'),
          },
          {
            title: t('about.ecosystem.items.1.title'),
            description: t('about.ecosystem.items.1.description'),
          },
          {
            title: t('about.ecosystem.items.2.title'),
            description: t('about.ecosystem.items.2.description'),
          },
        ],
      },
      differentiators: {
        title: t('about.differentiators.title'),
        quote: t('about.differentiators.quote'),
        items: [
          {
            title: t('about.differentiators.items.0.title'),
            description: t('about.differentiators.items.0.description'),
          },
          {
            title: t('about.differentiators.items.1.title'),
            description: t('about.differentiators.items.1.description'),
          },
          {
            title: t('about.differentiators.items.2.title'),
            description: t('about.differentiators.items.2.description'),
          },
          {
            title: t('about.differentiators.items.3.title'),
            description: t('about.differentiators.items.3.description'),
          },
        ],
      },
    },
    finalCta: {
      title: t('finalCta.title'),
      button: t('finalCta.button'),
    },
    footer: {
      rights: t('footer.rights'),
      terms: t('footer.terms'),
      compliance: t('footer.compliance'),
      support: t('footer.support'),
      disclaimer: t('footer.disclaimer'),
      credit: t('footer.credit'),
    },
    crypto: [
      { name: 'Bitcoin', symbol: 'BTC', icon: '/assets/coins/btc.png' },
      { name: 'Ethereum', symbol: 'ETH', icon: '/assets/coins/eth.png' },
      { name: 'Solana', symbol: 'SOL', icon: '/assets/coins/sol.png' },
      { name: 'BNB', symbol: 'BNB', icon: '/assets/coins/bnb.png' },
      { name: 'Tether', symbol: 'USDT', icon: '/assets/coins/usdt.png' },
      { name: 'USD Coin', symbol: 'USDC', icon: '/assets/coins/usdc.png' },
    ],
    form: {
      title: t('form.title'),
      subtitle: t('form.subtitle'),
      accountType: t('form.accountType'),
      pf: t('form.pf'),
      pj: t('form.pj'),
      pfSection: t('form.pfSection'),
      fullName: t('form.fullName'),
      cpf: t('form.cpf'),
      cpfHint: t('form.cpfHint'),
      birthDate: t('form.birthDate'),
      rg: t('form.rg'),
      cnh: t('form.cnh'),
      foreigner: t('form.foreigner'),
      email: t('form.email'),
      phone: t('form.phone'),
      phoneHint: t('form.phoneHint'),
      pep: t('form.pep'),
      pepPosition: t('form.pepPosition'),
      addressSection: t('form.addressSection'),
      cep: t('form.cep'),
      street: t('form.street'),
      number: t('form.number'),
      complement: t('form.complement'),
      district: t('form.district'),
      city: t('form.city'),
      state: t('form.state'),
      foreignStreet: t('form.foreignStreet'),
      foreignNumber: t('form.foreignNumber'),
      foreignComplement: t('form.foreignComplement'),
      foreignDistrict: t('form.foreignDistrict'),
      foreignCity: t('form.foreignCity'),
      foreignState: t('form.foreignState'),
      foreignZip: t('form.foreignZip'),
      foreignCountry: t('form.foreignCountry'),
      documentsSection: t('form.documentsSection'),
      docFront: t('form.docFront'),
      docBack: t('form.docBack'),
      selfie: t('form.selfie'),
      proofOfAddress: t('form.proofOfAddress'),
      docHint: t('form.docHint'),
      selfieHint: t('form.selfieHint'),
      proofHint: t('form.proofHint'),
      companySection: t('form.companySection'),
      companyName: t('form.companyName'),
      tradeName: t('form.tradeName'),
      cnpj: t('form.cnpj'),
      foundationDate: t('form.foundationDate'),
      cnae: t('form.cnae'),
      companyEmail: t('form.companyEmail'),
      companyPhone: t('form.companyPhone'),
      legalNature: t('form.legalNature'),
      fiscalAddress: t('form.fiscalAddress'),
      adminSection: t('form.adminSection'),
      adminName: t('form.adminName'),
      adminCpf: t('form.adminCpf'),
      adminEmail: t('form.adminEmail'),
      adminPhone: t('form.adminPhone'),
      companyDocsSection: t('form.companyDocsSection'),
      articles: t('form.articles'),
      articlesHint: t('form.articlesHint'),
      cnpjCard: t('form.cnpjCard'),
      adminIdFront: t('form.adminIdFront'),
      adminIdBack: t('form.adminIdBack'),
      companyProof: t('form.companyProof'),
      ecnpj: t('form.ecnpj'),
      ecnpjHint: t('form.ecnpjHint'),
      acceptTermsStart: t('form.acceptTermsStart'),
      terms: t('form.terms'),
      termsMiddle: t('form.termsMiddle'),
      privacy: t('form.privacy'),
      cancel: t('form.cancel'),
      submit: t('form.submit'),
    },
  };
}
